"""
router.py

This module defines the router for handling requests related to Language Model (LLM) agents.

It includes endpoints for health checks and running the LLM agent based on incoming requests.
"""

from fastapi import APIRouter

from .constants import AGENT_NAME, router_default_response
from .llm_agent import run_agent
from .schemas import RequestData

router = APIRouter(
    prefix=f"/{AGENT_NAME}",
    tags=[AGENT_NAME],
    dependencies=[],
    responses=router_default_response,
)


@router.post(
    "/",
    description="Endpoint for running the LLM agent based on the incoming request data.",
)
def run(request: RequestData):
    """
    Endpoint for running the LLM agent based on the incoming request data.

    Parameters:
        request (RequestData): The request data containing input for the LLM agent.

    Returns:
        str: The response generated by the LLM agent.
    """
    args_dict = request.model_dump()
    response = run_agent(**args_dict)
    return response
